# Generated by Django 5.2.4 on 2025-08-10 18:44

import common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner (easy level, best for training)'), ('intermediate', 'Intermediate (medium level, lots of fun)'), ('advanced', 'Advanced (high level, for skilled raiders)'), ('hard', 'Hard (expert level, for bike sports enthusiasts)'), ('extreme', 'Extreme (extremal level, only top thrill seekers go here)')], default='beginner', max_length=100)),
                ('type', models.CharField(choices=[('road', 'Road trip (best for road and gravel bike owners)'), ('urban', 'Urban exploring (riding across towns and cities)'), ('mixed', 'Mixed type route (both nature and urban locations)'), ('crosscountry', 'CrossCountry classic (into the wild)'), ('competition', 'CrossCountry competition racetrack (best for CC enthusiasts practicing)'), ('allmountain', 'AllMountain route type (both uphills and downhills - mountains at its best)'), ('trail', 'Trail (prepared tracks, mostly downhills)'), ('enduro', 'Enduro (same as trails, but more technical and extreme)'), ('free', 'FreeRide (explore the unexplored)'), ('downhill', 'Downhill (classic DH tracks)')], default='allmountain', max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('start_point', models.CharField(max_length=150)),
                ('end_point', models.CharField(max_length=150)),
                ('is_circular', models.BooleanField(default=False)),
                ('map_image', models.URLField(blank=True, null=True)),
                ('route_photo', models.ImageField(blank=True, null=True, upload_to='upload/', validators=[common.validators.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
