# Generated by Django 5.2.4 on 2025-08-09 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('city', 'City Bike'), ('gravel', 'Gravel Bike'), ('hybrid', 'Hybrid Bike'), ('mtb', 'Mountain Bike (MTB)'), ('road', 'Road Bike'), ('touring', 'Touring Bike')], default='mtb', max_length=50)),
                ('geometry', models.CharField(choices=[('rigid', 'Rigid Frame (no suspension)'), ('hardtail', 'Hardtail Frame (front suspension)'), ('full', 'Full Suspension Frame (front and rear suspension)')], default='hardtail', max_length=100)),
                ('is_ebike', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('wheel_size', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
