# Generated by Django 5.2.4 on 2025-08-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='is_mullet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bike',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='wheel_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
