# Generated by Django 5.2.4 on 2025-08-11 00:20

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(validators=[common.validators.validate_current_date]),
        ),
    ]
