# Generated by Django 5.2.4 on 2025-08-09 00:52

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', validators=[common.validators.validate_image_size]),
        ),
    ]
